name:Release tcppc-go

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        default: 'linux'
        required: true
      arch:
        description: 'Architecture'
        default: 'arm'
        required: true
      output:
        description: 'Output file name'
        default: 'tcppc-go-linux-armv7'
        required: true

jobs:
  build-cli:
    name: Build cli
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ${{ github.event.inputs.os }}
            arch: ${{ github.event.inputs.arch }}
            output: ${{ github.event.inputs.output }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      GOARM: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
          cache: true

      - name: Initialize Go module
        run: |
          go mod init github.com/md-irohas/tcppc-go
          go mod tidy

      - name: Build
        run: |
          mkdir -p target
          go build -trimpath -ldflags "-w -s -extldflags '-static'" -o target/${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.os }}-${{ matrix.arch }}
          path: target/*
